//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub ordinal: i32,
    pub board_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::category_tags::Entity")]
    CategoryTags,
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Boards,
}

impl Related<super::category_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryTags.def()
    }
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
